// @ts-nocheck
import * as __fd_glob_48 from "../content/docs/public-packages/morph/index.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/public-packages/morph/api-reference.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/public-packages/graphql-client/setup-and-codegen.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/public-packages/graphql-client/optimistic-mutations.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/public-packages/graphql-client/index.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/public-packages/graphql-client/architecture-and-limits.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/monorepo/workspace-map.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/monorepo/technology-stack.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/monorepo/overview.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/monorepo/dependency-flow.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/public-packages/overview.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/getting-started/environment.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/getting-started/commands.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/internal-packages/storage.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/internal-packages/overview.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/internal-packages/logging.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/internal-packages/graphql.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/internal-packages/environment-and-constants.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/internal-packages/database.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/internal-packages/configuration.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/internal-packages/auth.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/internal-packages/api.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/contributing/testing-and-quality.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/contributing/releases-and-ci.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/contributing/development-workflow.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/contributing/commits-and-changesets.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/architecture/request-lifecycle.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/architecture/media-and-storage.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/architecture/jobs-email-and-logging.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/architecture/graphql-workflow.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/architecture/data-and-validation.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/architecture/authentication.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/apps/web.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/apps/server.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/apps/overview.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/apps/extension.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/apps/docs.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/public-packages/morph/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/public-packages/graphql-client/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/public-packages/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/monorepo/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/internal-packages/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/contributing/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/architecture/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/apps/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "apps/meta.json": __fd_glob_1, "architecture/meta.json": __fd_glob_2, "contributing/meta.json": __fd_glob_3, "getting-started/meta.json": __fd_glob_4, "internal-packages/meta.json": __fd_glob_5, "monorepo/meta.json": __fd_glob_6, "public-packages/meta.json": __fd_glob_7, "public-packages/graphql-client/meta.json": __fd_glob_8, "public-packages/morph/meta.json": __fd_glob_9, }, {"index.mdx": __fd_glob_10, "apps/docs.mdx": __fd_glob_11, "apps/extension.mdx": __fd_glob_12, "apps/overview.mdx": __fd_glob_13, "apps/server.mdx": __fd_glob_14, "apps/web.mdx": __fd_glob_15, "architecture/authentication.mdx": __fd_glob_16, "architecture/data-and-validation.mdx": __fd_glob_17, "architecture/graphql-workflow.mdx": __fd_glob_18, "architecture/jobs-email-and-logging.mdx": __fd_glob_19, "architecture/media-and-storage.mdx": __fd_glob_20, "architecture/request-lifecycle.mdx": __fd_glob_21, "contributing/commits-and-changesets.mdx": __fd_glob_22, "contributing/development-workflow.mdx": __fd_glob_23, "contributing/releases-and-ci.mdx": __fd_glob_24, "contributing/testing-and-quality.mdx": __fd_glob_25, "internal-packages/api.mdx": __fd_glob_26, "internal-packages/auth.mdx": __fd_glob_27, "internal-packages/configuration.mdx": __fd_glob_28, "internal-packages/database.mdx": __fd_glob_29, "internal-packages/environment-and-constants.mdx": __fd_glob_30, "internal-packages/graphql.mdx": __fd_glob_31, "internal-packages/logging.mdx": __fd_glob_32, "internal-packages/overview.mdx": __fd_glob_33, "internal-packages/storage.mdx": __fd_glob_34, "getting-started/commands.mdx": __fd_glob_35, "getting-started/environment.mdx": __fd_glob_36, "getting-started/installation.mdx": __fd_glob_37, "public-packages/overview.mdx": __fd_glob_38, "monorepo/dependency-flow.mdx": __fd_glob_39, "monorepo/overview.mdx": __fd_glob_40, "monorepo/technology-stack.mdx": __fd_glob_41, "monorepo/workspace-map.mdx": __fd_glob_42, "public-packages/graphql-client/architecture-and-limits.mdx": __fd_glob_43, "public-packages/graphql-client/index.mdx": __fd_glob_44, "public-packages/graphql-client/optimistic-mutations.mdx": __fd_glob_45, "public-packages/graphql-client/setup-and-codegen.mdx": __fd_glob_46, "public-packages/morph/api-reference.mdx": __fd_glob_47, "public-packages/morph/index.mdx": __fd_glob_48, });