import { FileSystem, Path } from "@effect/platform";
import { BunContext, BunRuntime } from "@effect/platform-bun";
import dotenv from "dotenv";
import { Effect } from "effect";

dotenv.config({
  path: "../../apps/server/.env",
});

const GRAPHQL_MODEL_SUFFIX = ".graphql.ts";
const TS_EXTENSION = /\.ts$/;

export const collectGraphqlImports = Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  const scriptDir = import.meta.dirname;
  const modelsRoot = path.resolve(
    scriptDir,
    "../../../packages/api/src/models"
  );
  const generatedFile = path.resolve(scriptDir, "../gen/generated-imports.ts");

  const entries = yield* fs.readDirectory(modelsRoot, { recursive: true });
  const files = entries
    .filter((entry) => entry.endsWith(GRAPHQL_MODEL_SUFFIX))
    .sort((a, b) => a.localeCompare(b));

  const imports = files
    .map((file) => {
      const modulePath = file.replace(TS_EXTENSION, "");
      return `import '../../api/src/models/${modulePath}';`;
    })
    .join("\n");

  yield* fs.writeFileString(
    generatedFile,
    [
      "// This file is generated by packages/graphql/scripts/collect-graphql-imports.ts.",
      "// Do not edit it by hand.",
      imports,
      "",
    ].join("\n")
  );
});

if (import.meta.main) {
  const main = Effect.gen(function* () {
    yield* collectGraphqlImports;
    yield* Effect.log("✅ 📋 GraphQL imports collected successfully");
  });

  // @effect-diagnostics-next-line effect/strictEffectProvide:off
  BunRuntime.runMain(main.pipe(Effect.provide(BunContext.layer)));
}
